dist: focul

language: python

sudo: enabled

python:
   - "3.6"
   - "3.7"
   - "3.8"

addons:
  apt:
     packages:
       # GCC 4.9
       # - g++-4.9
       # MPICH
       - mpich
       - libmpich-dev
       # OpenMPI
       # - openmpi-bin
       # - libopenmpi-dev
       
branches:
  only:
    - test
env:
  - USE_CUDA_PARALLEL="00"    # serial
  - USE_CUDA_PARALLEL="01"    # parallel
  - USE_CUDA_PARALLEL="10"    # cuda
  - USE_CUDA_PARALLEL="11"    # parallel + cuda  
    
jobs:
  include:
    - os: osx
      osx_image: xcode11.2
      compiler: clang
      language: shell
      name: "Mac: Serial"
      env: USE_CUDA_PARALLEL=00 

# command to install dependencies
before_install:
  - >
    if [ "${USE_CUDA_PARALLEL}" = "11" ] || [ "${USE_CUDA_PARALLEL}" = "10" ]; then
    ./travis/add_cuda.sh;
    export PATH=/usr/local/cuda-11.1/bin:$PATH;
    fi
  - >
    if [ "${USE_CUDA_PARALLEL}" = "01" ] || [ "${USE_CUDA_PARALLEL}" = "11" ]; then
    which mpicc;
    pip3 install mpi4py;
    python3 -c "import mpi4py;print(mpi4py.get_include())";
    fi

install:
  - pip install -r requirements.txt

script:
  - echo $USE_CUDA_PARALLEL
  - echo $PATH
  - PYTHONVERSION=$(python3 -c "import os;print(os.path.basename(os.path.dirname(os.__file__))[-3:])");
  - PYTHONLIB=${TRAVIS_BUILD_DIR}/../lib/python${PYTHONVERSION};
  - export PYTHONPATH=$PYTHONLIB/site-packages:$PYTHONPATH  
  - >
    if [ "${USE_CUDA_PARALLEL}" = "00" ]; then  
    python3 setup.py install --prefix=$TRAVIS_BUILD_DIR/..;
    cd $TRAVIS_BUILD_DIR/test;
    python3 ../examples/ex1.py;
    fi
  - >
    if [ "${USE_CUDA_PARALLEL}" = "01" ]; then
    python3 setup.py install --with-parallel --prefix=$TRAVIS_BUILD_DIR/..; 
    which mpicc;
    cd $TRAVIS_BUILD_DIR/test;
    mpirun -np 2 python3 ../examples/ex1p.py;    
    fi
  - >
    if [ "${USE_CUDA_PARALLEL}" = "10" ]; then
    python3 setup.py install --with-cuda --prefix=$TRAVIS_BUILD_DIR/..; 
    which nvcc;
    cd $TRAVIS_BUILD_DIR/test;
    fi
# python3 ../examples/ex1.py --d='cuda' --pa;    
  - >
    if [ "${USE_CUDA_PARALLEL}" = "11" ]; then
    which nvcc;
    which mpicc;
    python3 setup.py install --with-cuda --with-paralel --prefix=$TRAVIS_BUILD_DIR/..;
    cd $TRAVIS_BUILD_DIR/test;
    fi
  - python3 --version    
# mpirun -np2 python3 ../examples/ex1p.py --d='cuda' --pa;




  



